// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jz42T-C7Exnb4kifICBhXTJGl1t7Nsg',
    appId: '1:95233541141:web:d27174ea9c9803811afa1c',
    messagingSenderId: '95233541141',
    projectId: 'flutterstudy2-631b2',
    authDomain: 'flutterstudy2-631b2.firebaseapp.com',
    storageBucket: 'flutterstudy2-631b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3LMu-Uz6C3clHjyOU0_f4mWGtAdB8bD8',
    appId: '1:95233541141:android:6ce0a8c00ba5ef281afa1c',
    messagingSenderId: '95233541141',
    projectId: 'flutterstudy2-631b2',
    storageBucket: 'flutterstudy2-631b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC1f8hPf52saOV0OM5avsI52BvqlJBbVA',
    appId: '1:95233541141:ios:5b55b5df164664441afa1c',
    messagingSenderId: '95233541141',
    projectId: 'flutterstudy2-631b2',
    storageBucket: 'flutterstudy2-631b2.appspot.com',
    iosClientId: '95233541141-ovcjhvs16obvtleueaannrhbohdvqj62.apps.googleusercontent.com',
    iosBundleId: 'com.wilddevseok.finstagram',
  );
}
